import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { ModeToggle } from "@/components/ModeTogle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sensor Data",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="absolute right-10 top-10">
            <ModeToggle />
            </div>
            {children}
          </ThemeProvider>
        </body>

    </html>
  );
}
